---
title: "Writing function"
output: html_document
date: "2024-11-14"
---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplots.continuous.colour = "virids",
  ggplot2.continuous.fill = "virids"
)

scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## do something simple
make sure ramdom data set sd around 3
```{r}
x_vec = rnorm(30, mean = 5, sd = 3)

(x_vec - mean(x_vec)) / sd(x_vec)
```

i want some function compute z-sores
```{r}
z_scores = function(x) {
  
  if (!is.numeric(x)){
    stop("input must be numeric")
  }
  
  if (length(x) < 3) {
    stop("input must have at least three numbers")
  }
  
mean_x = mean(x)
sd_x = sd(x)

tibble(
  mean = mean_x,
  sd = sd_x
)



}


z_scores(x_vec)
```

check that the function works.
```{r}
x_vec = rnorm(100, mean = 3, sd =4)

```


Try me function on some other things

these should give errors
```{r, error = TRUE}
z_scores(3)
z_scores("my name is Jeff")
z_scores(mtcars) #cannot calculate mean of character vector
z_scores(c(TRUE, TRUE,FALSE, TRUE)) # mean of (1,1,0,1)

```


## multiple inputs
do this with function
```{r}
sim_data =
  tibble(
    x = rnorm (n = 100, mean = 4, sd = 3)
  )

sim_data |>
  summarize (
    mean = mean(x),
    sd = sd(x)
  )

```



```{r}
sim_mean_sd = function(n, mu, sigma) #provide default value for these
  {
  
  sim_data =
  tibble(
    x = rnorm (n = n, mean = mu, sd = sigma)
  )

sim_data |>
  summarize (
    mean = mean(x),
    sd = sd(x)
  )
  
  sim_mean_sd(sample_size = 100, mu = 6, sigma = 3) #using these rather than default value
}
```

## let's review Napoleon Dynamite
 
turn code into function
```{r}
url = ""

read_page_reviews = functions(url) {
  dynamite_html = read_html(url)
  
  review_titles = 
    dynamite_html |>
    html_nodes(".a-text-bold span")|>
    html_text()
  
  review_stars = 
    dynamite_html |>
    html_nodes ("#cm_cr-review_list . review_rating") |>
    html_text ()|>
    str_extract("^\\d") |>
    as.numeric()
  
  review_text = 
    dynamite_html |>
    html_nodes(".review-text-content span") |>
    html_text () |>
    str_replace_all ("\n","")|>
    str_trim()
  
  reviews = 
    tibble (
      tittle = review_tittles,
      stars = review_stars,
      text = review_text
    )
  
    reviews
}
```


let's read a few pages of reviews
```{r}
url = 
  dynamite_urls = str_c (dynamite_url_base, 1:5)

all_reviews = 
  bind_rows(
    read_page_reviews(dynamite_urls[1]),
    read_page_reviews(dynamite_urls[2]),
    read_page_reviews(dynamite_urls[3]),
    read_page_reviews(dynamite_urls[4]),
    read_page_reviews(dynamite_urls[5]),
  )

```


## mean scoping example

```{r}
f = function(x1) {
  z = x1 + x2
  z
}

x = 1
y = 2

f(x = y)
```
















